### ISSUE TITLE
AttributeError: module 'tensorflow._api.v2.io' has no attribute 'MakeDirs'

### ISSUE THREAD

**Issue by mehmood-kashif** [farazBhatti/semanticSegmentation_for_beginners#1]
I have faced some errors regarding the TensorFlow version, I have searched the error but didn't get any satisfactory answer, please help I should be thankful

**Comment by farazBhatti** [comment]
@kashifblessed try installing TensorFlow version 1.13.1. code has not been tested using tf 2.0. Also you can try to change  tf.gfile.* to tf.io.gfile.*

**Comment by mehmood-kashif** [comment]
it's worked after I downgrade my Tensorflow version, Thankyou so much
